### ISSUE TITLE
Color for bdd script 

### ISSUE THREAD

**Issue by JulienB37** [sirap-group/generate-swap-project#110]
When we use pipeline:test script we can see the result with colors (red/green) in the terminal. But when we use bdd script to develop we don't have the colors.

**Comment by rbecheras** [comment]
feature branch created: https://github.com/sirap-group/generate-swap-project/tree/110-color-for-bdd-script

**Comment by rbecheras** [comment]
The issue come from the usage of `shelljs` and need an enhancement from that project.

https://github.com/sirap-group/generate-swap-project/blob/acfc10949f2ce7e1e0bf7fe30c882a7a7c25775a/scripts/gulp-tasks/watch.js#L36

An issue already exist for this feature request in shelljs: https://github.com/shelljs/shelljs/issues/86

**Comment by rbecheras** [comment]
Enhancement released in `v1.4.0`
